COMMAND_OPEN = 'open'
COMMAND_CLOSE = 'close'

CONF_API = 'api'
CONF_OPEN_GARAGE_PIN = 'open_garage_pin'
CONF_CLOSE_GARAGE_PIN = 'close_garage_pin'
CONF_TOGGLE_GARAGE_PIN = 'toggle_garage_pin'
CONF_INVERT_RELAY = 'invert_relay'
CONF_POSITIONS = 'positions'
CONF_PIN = 'pin'
CONF_ENTITY_ID = 'entity_id'
CONF_NAME = 'name'
CONF_INTERACTIVE = 'interactive'

API_MQTT = 'mqtt'
API_HASS = 'hass'

POSITION_CLOSED = 'closed'
POSITION_OPEN = 'open'

ENTITY_ID = 'entity_id'
SERVICE = 'service'
SERVICE_DATA = 'service_data'
SERVICE_OPEN = 'cover.open_cover'
SERVICE_CLOSE = 'cover.close_cover'
STATE = 'state'
CURRENT_POSITION = 'current_position'

TEMPLATE_ENTITY_ID = '$ENTITY_ID'
TEMPLATE_SERVICE = '$SERVICE'
TEMPLATE_STATE = '$STATE'
TEMPLATE_ATTR_CURRENT_POSITION = '$CURRENT_POSITION'
